server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

#设置Feign的超时控制，避免默认时长覆盖@HystrixProperty注解的设定时长
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
  #开启@FeignClient注解的Hystrix功能，能指定fallback类
  hystrix:
    enabled: true
#设置@FeignClient注解的Hystrix功能的全局超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000